import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service — ThinkDeeper",
  description: "Understand the terms that govern your use of the ThinkDeeper platform.",
};

const governingLaw = "State of California, USA";

export default function TermsPage() {
  return (
    <section className="mx-auto max-w-3xl space-y-8 px-6 py-16">
      <header className="space-y-4">
        <h1 className="text-3xl font-semibold">Terms of Service</h1>
        <p className="text-sm text-foreground/70">Effective date: March 1, 2025</p>
        <p>
          These Terms of Service (the &ldquo;Terms&rdquo;) govern your access to and use of the
          ThinkDeeper website, mobile experiences, APIs, and related services (collectively, the
          &ldquo;Services&rdquo;). By creating an account, accessing, or using the Services, you agree
          to these Terms and our Privacy Policy. If you do not agree, do not use the Services.
        </p>
      </header>

      <section className="space-y-4">
        <h2 className="text-2xl font-semibold">1. Eligibility &amp; Account Registration</h2>
        <p>
          You must be at least 13 years old (or the minimum age in your jurisdiction) to use the
          Services. When you register, you must provide accurate and complete information, maintain
          the security of your credentials, and promptly update information that changes. You are
          responsible for all activity that occurs under your account.
        </p>
      </section>

      <section className="space-y-4">
        <h2 className="text-2xl font-semibold">2. Acceptable Use</h2>
        <ul className="list-disc space-y-3 pl-6">
          <li>Use the Services only for personal and lawful purposes.</li>
          <li>Do not upload content that is unlawful, defamatory, discriminatory, or infringes third-party rights.</li>
          <li>Do not attempt to probe, scan, or test the vulnerability of the Services or circumvent security measures.</li>
          <li>Do not copy, distribute, reverse engineer, or exploit the Services except as expressly permitted.</li>
          <li>Do not use the Services to develop or train competing models without prior written permission.</li>
        </ul>
      </section>

      <section className="space-y-4">
        <h2 className="text-2xl font-semibold">3. Subscription &amp; Billing</h2>
        <p>
          Certain features may require a paid subscription or one-time purchase. Prices are listed at
          the point of sale and may change upon notice. Unless otherwise stated, fees are non-refundable.
          Taxes and payment processor fees may apply. You authorize us to charge the payment method
          associated with your account.
        </p>
      </section>

      <section className="space-y-4">
        <h2 className="text-2xl font-semibold">4. User Content &amp; License</h2>
        <p>
          You retain ownership of content you submit through the Services (&ldquo;User Content&rdquo;).
          By submitting User Content, you grant ThinkDeeper a worldwide, non-exclusive, royalty-free
          license to host, store, reproduce, modify, and display that content solely to operate,
          improve, and provide the Services. You represent and warrant that you have the rights
          necessary for the content you submit and that our use will not infringe or violate third-party rights.
        </p>
      </section>

      <section className="space-y-4">
        <h2 className="text-2xl font-semibold">5. AI-Generated Output</h2>
        <p>
          The Services may provide suggestions or feedback generated by artificial intelligence. Such
          output is provided for informational purposes only and may be inaccurate or incomplete.
          You are solely responsible for reviewing AI-generated content before relying on it. ThinkDeeper
          makes no warranties regarding AI output and disclaims liability arising from your reliance on it.
        </p>
      </section>

      <section className="space-y-4">
        <h2 className="text-2xl font-semibold">6. Feedback</h2>
        <p>
          If you provide feedback, ideas, or suggestions, you grant us a perpetual, irrevocable,
          royalty-free license to use that feedback without restriction or obligation to you.
        </p>
      </section>

      <section className="space-y-4">
        <h2 className="text-2xl font-semibold">7. Third-Party Services</h2>
        <p>
          The Services may integrate or link to third-party platforms. Your use of those services is
          governed by their terms and policies. ThinkDeeper is not responsible for third-party services
          and does not endorse them.
        </p>
      </section>

      <section className="space-y-4">
        <h2 className="text-2xl font-semibold">8. Termination</h2>
        <p>
          We may suspend or terminate your access to the Services at any time for conduct that violates
          these Terms, poses a security risk, or is otherwise harmful. You may stop using the Services
          at any time, and you may request account deletion subject to applicable law.
        </p>
      </section>

      <section className="space-y-4">
        <h2 className="text-2xl font-semibold">9. Disclaimers</h2>
        <p>
          THE SERVICES ARE PROVIDED &ldquo;AS IS&rdquo; WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR
          IMPLIED, INCLUDING IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE,
          AND NON-INFRINGEMENT. WE DO NOT WARRANT THAT THE SERVICES WILL BE UNINTERRUPTED, SECURE, OR ERROR-FREE.
        </p>
      </section>

      <section className="space-y-4">
        <h2 className="text-2xl font-semibold">10. Limitation of Liability</h2>
        <p>
          TO THE MAXIMUM EXTENT PERMITTED BY LAW, THINKDEEPER AND ITS SUPPLIERS WILL NOT BE LIABLE FOR
          ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR FOR ANY LOSS OF
          PROFITS OR REVENUE. OUR TOTAL LIABILITY FOR ANY CLAIM ARISING OUT OF THESE TERMS OR THE
          SERVICES WILL NOT EXCEED THE GREATER OF (A) $100 OR (B) THE AMOUNTS YOU PAID TO US IN THE
          12 MONTHS PRECEDING THE CLAIM.
        </p>
      </section>

      <section className="space-y-4">
        <h2 className="text-2xl font-semibold">11. Indemnification</h2>
        <p>
          You agree to defend, indemnify, and hold harmless ThinkDeeper, its affiliates, and their
          respective officers, directors, and employees from any claims or demands arising from
          your use of the Services, your User Content, or your violation of these Terms.
        </p>
      </section>

      <section className="space-y-4">
        <h2 className="text-2xl font-semibold">12. Governing Law &amp; Dispute Resolution</h2>
        <p>
          These Terms are governed by the laws of the {governingLaw}, without regard to conflict of law
          principles. The parties agree to the exclusive jurisdiction of the state and federal courts
          located in San Francisco County, California, for any disputes arising out of these Terms,
          except where prohibited by law.
        </p>
      </section>

      <section className="space-y-4">
        <h2 className="text-2xl font-semibold">13. Changes to These Terms</h2>
        <p>
          We may update these Terms from time to time. If we make material changes, we will provide
          notice (e.g., via email or in-app notification). Continued use of the Services after the
          effective date of revised Terms constitutes acceptance of the changes.
        </p>
      </section>

      <section className="space-y-4">
        <h2 className="text-2xl font-semibold">14. Contact</h2>
        <p>
          If you have questions about these Terms, contact us at{" "}
          <a className="underline" href="mailto:legal@thinkdeeper.app">
            legal@thinkdeeper.app
          </a>
          .
        </p>
      </section>
    </section>
  );
}

